### ISSUE TITLE
Why does my Raspberry Pi 4B always restart when I run this project

### ISSUE THREAD

**Issue by angryhen** [Qengineering/TensorFlow_Lite_SSD_RPi_32-bits#1]
No matter if I overclock or not, it will always restart automatically when the program start running，and my Raspberry Pi is 4B and  8g RAM.I make sure the program is correct.

**Comment by Qengineering** [comment]
Dear angryhen,

Sorry to hear about your problem. Your program appears to be fetching a mutated instruction. This can cause the known segment error, or in other cases a jump to an unknown location, which could cause a program to restart. I'm afraid there's more at hand here, as almost every part of the program calls libraries, such as OpenCV, or calls to the operating system. Try to isolate the error by commenting out lines. Run again and see if it fixes the problem. In the end you got the instruction here goes wrong. Probably some loading from file call. Remember, this little program on GitHub is checked by us several times and downloaded many times. Never a problem, that makes me suspect that a library on your RPi is no longer sane.

**Comment by angryhen** [comment]
Thank you for your patient reply.At the default cpu frequency,the model ran for a while and had 9fps,.But the Raspberry Pi will still restart automatically soon.

**Comment by Qengineering** [comment]
Dear angryhen,

Let's try to reproduce the error. Which version of OpenCV you have installed? Is it according our guide? Which version of TensorFlow Lite do you use? I want to copy your system as much as possible to see what's happening when we run it at the office.

**Comment by angryhen** [comment]
> Dear angryhen,
> 
> Let's try to reproduce the error. Which version of OpenCV you have installed? Is it according our guide? Which version of TensorFlow Lite do you use? I want to copy your system as much as possible to see what's happening when we run it at the office.

Hi:
After investigation, I found that it was a power issue. And changing to a new power supply, then there will be no automatic restart.Thanks

**Comment by Qengineering** [comment]
Glad to hear you solved it!
