### ISSUE TITLE
Segmentation Fault on TFLite Model for Object Detection

### ISSUE THREAD

**Issue by taminhtoan2601** [Qengineering/TensorFlow_Lite_SSD_RPi_32-bits#3]
Hello, 

Firstly, thank you for your instruction for running TFLite model on RPi, I successfully ran your model for object detection that you gave on github. When I replaced your model by my model (that I trainned following the instruction of Tensorflow Object Detection API and have a model .tflite like you), the code in c++ has an error: Segmentation Fault and finished the execution. Do you have any idea for resolving that? 

Thank you so much.
Toan.

**Comment by Qengineering** [comment]
Dear @taminhtoan2601 ,

I'm sorry to hear about your problem.
As you mentioned, the software works fine with the TF model provided, no bugs there.
If the new model is causing problems, it is almost certain that the TFLite conversion has somehow failed.
Segmentation errors are often related to memory problems. Retrieving variables 'outside' the memory bank, for example.
You could try running the TFLite model in a Python environment. Python sometimes gives you more information about where things are going wrong.

**Comment by taminhtoan2601** [comment]
Thank you for your quickly answer. 

I successfully ran my tflite model in Python on RPI4 but the FPS is slowly, so I decided to try your code for running in C++ instead of Python. So in C++,  I met that error. 

Thank you again.

**Comment by taminhtoan2601** [comment]
I will look at the part of conversion of TFLite model. I think it will work fine with the quantized model.

**Comment by taminhtoan2601** [comment]
Hello, 
The problem was label (my labelmap text file is just one line "hand"). The original model you took from tensorflow site is for coco dataset, where class id 0 is background, so in the code, you incremented recognized class id.
Delete + 1 at the line 74 (int det_index = (int) detection_classes[i] + 1) in the file MobileNetV1.cpp, and the segmentation fault should be fixed.
Have a nice day!

**Comment by Qengineering** [comment]
Nice to hear you could fix it!
